# Generated by Django 4.2.2 on 2023-07-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='gender',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='team',
            name='region',
        ),
    ]
