# Generated by Django 4.2.2 on 2023-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_team_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='pics/default_prof_pic.png', upload_to='pics'),
        ),
    ]
