# Generated by Django 4.2.2 on 2023-07-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_team_admin_team_players_user_teams_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
