# Generated by Django 4.2.2 on 2023-07-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_name', models.CharField()),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_events',
            field=models.ManyToManyField(to='portal.event'),
        ),
    ]
