# Generated by Django 4.2.2 on 2023-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_user_teams_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='portalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='portal_options',
            field=models.ManyToManyField(to='portal.portaloptions'),
        ),
    ]
