# Generated by Django 4.2.2 on 2023-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_portaloptions_team_portal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams_allowed',
            field=models.ManyToManyField(related_name='teams_allowed', to='portal.team'),
        ),
    ]
