# Generated by Django 4.2.2 on 2023-08-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_user_teams_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='team',
            name='password',
        ),
    ]
