# Generated by Django 4.2.2 on 2023-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_team_confirm_password_remove_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admin', to='portal.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='portal.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_events',
            field=models.ManyToManyField(blank=True, to='portal.event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams_allowed',
            field=models.ManyToManyField(blank=True, related_name='teams_allowed', to='portal.team'),
        ),
    ]
